//
//  testAutoComplete.swift
//  Stock_Search
//
//  Created by 高宇 on 4/21/16.
//  Copyright © 2016 Alfred_Gao. All rights reserved.
//


let countries = ["African Union",
                 "Andorra",
                 "Armenia",
                 "Austria",
                 "Bahamas",
                 "Barbados",
                 "Belarus",
                 "Belgium",
                 "Benin",
                 "Bolivia",
                 "Bosnia and Herzegovina",
                 "Botswana",
                 "Brazil",
                 "Bulgaria",
                 "Burkina Faso",
                 "Cameroon",
                 "Canada",
                 "Chad",
                 "Chile",
                 "China",
                 "Colombia",
                 "Congo",
                 "Czech Republic",
                 "Denmark",
                 "Egypt",
                 "England",
                 "Estonia",
                 "Finland",
                 "Flag Of Europe",
                 "France",
                 "Gabon",
                 "Germany",
                 "Germana",
                 "Germanu1",
                 "Germanu2",
                 "Germanu3",
                 "Germanu4",
                 "Germanu5",
                 "Germanu6",
                 "Germanu7",
                 "Germanu8",
                 "Germanu9",
                 "Germanu10",
                 "Germanu11",
                 "Great Britain",
                 "Hungary",
                 "Iceland",
                 "Iran",
                 "Ireland",
                 "Italy",
                 "Jamaica",
                 "Kuwait",
                 "Latvia",
                 "Liberia",
                 "Lithuania",
                 "Macedonia",
                 "Mali",
                 "Netherlands",
                 "New Zealand",
                 "Norway",
                 "Philippines",
                 "Poland",
                 "Portugal",
                 "Romania",
                 "Russian Federation",
                 "Slovakia",
                 "Slovenia",
                 "Spain",
                 "Sweden",
                 "Switzerland",
                 "Togo",
                 "Turkey",
                 "Ukraine",
                 "USA",
                 "Wales"]
